import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell } from "@/components/layout/AppShell";
import { useI18n } from "@/lib/i18n";
import { useAuth } from "@/lib/auth";
import { PermissionGate } from "@/components/PermissionGate";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CheckCircle2, ArrowRight, FileDown } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/demo-flow")({
  head: () => ({ meta: [{ title: "Demo Flow — JAAD CLOUD" }] }),
  component: () => (
    <PermissionGate perm="settings.manage" mode="page">
      <DemoFlowPage />
    </PermissionGate>
  ),
});

type Step = {
  n: number;
  ar: string;
  en: string;
  sayAr: string;
  sayEn: string;
  expectedAr: string;
  expectedEn: string;
  to: string;
};

const steps: Step[] = [
  {
    n: 1,
    ar: "نظرة عامة على لوحة التحكم",
    en: "Dashboard overview",
    sayAr: "ابدأ بعرض الصورة العامة للأعمال: مؤشرات المبيعات والمقبوضات والمصروفات.",
    sayEn: "Start with the business overview: sales, receipts, and expense indicators.",
    expectedAr: "بطاقات ملخصة + إجراءات سريعة + آخر النشاطات",
    expectedEn: "Summary cards + quick actions + recent activity",
    to: "/",
  },
  {
    n: 2,
    ar: "العملاء",
    en: "Customers",
    sayAr: "اعرض قائمة عملاء حقيقيين بأسلوب سعودي مع بيانات تواصل ورصيد.",
    sayEn: "Show realistic Saudi-style customers with contact info and balances.",
    expectedAr: "قائمة عملاء + إنشاء عميل + تفاصيل + رصيد",
    expectedEn: "Customer list + create + details + balance",
    to: "/customers",
  },
  {
    n: 3,
    ar: "المنتجات والخدمات",
    en: "Products & Services",
    sayAr: "وضّح فهرس المنتجات والخدمات مع سعر ووحدة وضريبة قيمة مضافة 15%.",
    sayEn: "Show the item catalog with price, unit, and 15% VAT.",
    expectedAr: "أصناف + خدمات + سعر + VAT",
    expectedEn: "Items + services + price + VAT",
    to: "/items",
  },
  {
    n: 4,
    ar: "إنشاء عرض سعر",
    en: "Create a quotation",
    sayAr: "أنشئ عرض سعر جديد بإضافة بنود وحساب الضريبة والإجمالي تلقائيًا.",
    sayEn: "Create a new quotation with lines, automatic VAT, and totals.",
    expectedAr: "ترقيم تلقائي + إجمالي + ضريبة + حالة Draft",
    expectedEn: "Auto-numbering + totals + VAT + Draft status",
    to: "/quotations",
  },
  {
    n: 5,
    ar: "إرسال وقبول العرض",
    en: "Send & accept the quotation",
    sayAr: "غيّر حالة العرض إلى مُرسَل ثم مقبول لإظهار سير العمل.",
    sayEn: "Move the quotation to Sent then Accepted to show the workflow.",
    expectedAr: "حالات: مسودة → مُرسَل → مقبول",
    expectedEn: "States: Draft → Sent → Accepted",
    to: "/quotations",
  },
  {
    n: 6,
    ar: "تحويل العرض إلى فاتورة",
    en: "Convert quotation to invoice",
    sayAr: "اعرض كيف يتم تحويل العرض المقبول إلى فاتورة بنقرة واحدة.",
    sayEn: "Show one-click conversion from accepted quotation to invoice.",
    expectedAr: "فاتورة جديدة منسوخة من العرض",
    expectedEn: "New invoice copied from the quotation",
    to: "/invoices",
  },
  {
    n: 7,
    ar: "إصدار الفاتورة",
    en: "Issue the invoice",
    sayAr: "أصدر الفاتورة لتنتقل من مسودة إلى مُصدَرة ويتم ترحيل القيد تلقائيًا.",
    sayEn: "Issue the invoice to flip from Draft to Issued and auto-post the journal.",
    expectedAr: "حالة Issued + رقم نهائي + قفل التعديل",
    expectedEn: "Issued status + final number + edit locked",
    to: "/invoices",
  },
  {
    n: 8,
    ar: "تسجيل سند قبض",
    en: "Record a receipt voucher",
    sayAr: "سجّل دفعة من العميل وأظهر تحديث رصيد الفاتورة تلقائيًا.",
    sayEn: "Record a customer payment and show the invoice balance update.",
    expectedAr: "سند قبض + ربط بالفاتورة + قيد آلي",
    expectedEn: "Receipt + invoice link + automatic journal entry",
    to: "/receipts",
  },
  {
    n: 9,
    ar: "القيد المحاسبي الناتج",
    en: "Generated journal entry",
    sayAr: "افتح القيود لتُظهر القيد التلقائي الناتج عن الفاتورة وسند القبض.",
    sayEn: "Open journal to show the entries generated by the invoice and receipt.",
    expectedAr: "قيود متوازنة، مرحَّلة، غير قابلة للتعديل",
    expectedEn: "Balanced posted entries, edit locked",
    to: "/accounting/journal",
  },
  {
    n: 10,
    ar: "التقارير",
    en: "Reports",
    sayAr: "اعرض تقارير المبيعات وضريبة القيمة المضافة ومركز التقارير.",
    sayEn: "Show sales, VAT, and the reports center.",
    expectedAr: "تقارير جاهزة + فئات + تصدير لاحقًا",
    expectedEn: "Ready reports + categories + future export",
    to: "/reports",
  },
  {
    n: 11,
    ar: "سجل المراجعة",
    en: "Audit log",
    sayAr: "وضّح أن كل عملية حساسة مُسجَّلة بمَن قام بها ومتى ولماذا.",
    sayEn: "Show that every sensitive action is logged with who/when/what.",
    expectedAr: "سجل مفصّل قابل للتصفية",
    expectedEn: "Filterable detailed log",
    to: "/audit-log",
  },
  {
    n: 12,
    ar: "جاهزية النظام (اختياري)",
    en: "System readiness (optional)",
    sayAr: "اشرح باختصار أن قاعدة البيانات السحابية جاهزة للتفعيل عند الحاجة.",
    sayEn: "Briefly explain that the cloud database is ready to activate when needed.",
    expectedAr: "وضع البيانات + الفحص الجاف + سلامة البيانات",
    expectedEn: "Data mode + dry run + integrity",
    to: "/system-data-mode",
  },
];

function DemoFlowPage() {
  const { lang } = useI18n();
  const { session } = useAuth();
  const isOwner = session?.role === "owner";

  return (
    <AppShell>
      <div className="max-w-5xl mx-auto space-y-5">
        <header className="space-y-2">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div>
              <h1 className="text-2xl font-semibold">
                {lang === "ar" ? "تدفق العرض التجريبي — جاد كلاود" : "Demo Flow — JAAD CLOUD"}
              </h1>
              <p className="text-sm text-muted-foreground">
                {lang === "ar"
                  ? "تسلسل مقترح لعرض النظام على العميل خطوة بخطوة."
                  : "Recommended step-by-step sequence for presenting the system to a client."}
              </p>
            </div>
            <Button
              variant="outline"
              size="sm"
              disabled
              onClick={() => toast.message(lang === "ar" ? "قريبًا" : "Coming soon")}
              title={lang === "ar" ? "قريبًا" : "Coming soon"}
            >
              <FileDown className="size-4 me-1" />
              {lang === "ar" ? "تصدير ملخص العرض PDF" : "Export Demo Summary PDF"}
            </Button>
          </div>
          <div className="flex flex-wrap gap-2 text-xs">
            <Badge variant="secondary">{lang === "ar" ? "الوضع التجريبي" : "Demo Mode"}</Badge>
            <Badge variant="outline">{lang === "ar" ? "الكتابة على الباك اند معطّلة" : "Backend writes disabled"}</Badge>
            <Badge variant="outline">{lang === "ar" ? "ثنائي اللغة AR / EN" : "Bilingual AR / EN"}</Badge>
            <Badge variant="outline">{lang === "ar" ? "ضريبة القيمة المضافة 15%" : "VAT 15%"}</Badge>
            {!isOwner && (
              <Badge variant="destructive">
                {lang === "ar" ? "تظهر بالكامل لدور المالك فقط" : "Best viewed as Owner"}
              </Badge>
            )}
          </div>
        </header>

        <ol className="space-y-3">
          {steps.map((s) => (
            <li key={s.n} className="card-elevated p-4 rounded-lg">
              <div className="flex items-start gap-4">
                <div className="shrink-0 size-9 rounded-full bg-primary/10 text-primary font-semibold flex items-center justify-center">
                  {s.n}
                </div>
                <div className="flex-1 min-w-0 space-y-2">
                  <div className="flex flex-wrap items-center gap-2 justify-between">
                    <div>
                      <h2 className="font-semibold leading-tight">
                        {lang === "ar" ? s.ar : s.en}
                      </h2>
                      <p className="text-xs text-muted-foreground">
                        {lang === "ar" ? s.en : s.ar}
                      </p>
                    </div>
                    <Badge className="text-xs" variant="secondary">
                      <CheckCircle2 className="size-3 me-1" />
                      {lang === "ar" ? "جاهز" : "Ready"}
                    </Badge>
                  </div>
                  <p className="text-sm">
                    <span className="text-muted-foreground me-1">
                      {lang === "ar" ? "ماذا تقول:" : "What to say:"}
                    </span>
                    {lang === "ar" ? s.sayAr : s.sayEn}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    <span className="me-1">{lang === "ar" ? "النتيجة المتوقعة:" : "Expected:"}</span>
                    {lang === "ar" ? s.expectedAr : s.expectedEn}
                  </p>
                  <div>
                    <Link to={s.to as never}>
                      <Button size="sm" variant="outline">
                        {lang === "ar" ? "افتح الصفحة" : "Open page"}
                        <ArrowRight className="size-3 ms-1" />
                      </Button>
                    </Link>
                  </div>
                </div>
              </div>
            </li>
          ))}
        </ol>

        <footer className="text-xs text-muted-foreground space-y-1 pt-2">
          <p>
            {lang === "ar"
              ? "ملاحظة: البيانات تجريبية ولا تُكتب على قاعدة بيانات إنتاج. عند تفعيل السحابة لاحقًا، نفّذ Phase 2.1.2 Retry قبل أي اعتماد على الكتابة."
              : "Note: data is demo and not written to a production database. When the cloud is enabled later, run Phase 2.1.2 Retry before relying on writes."}
          </p>
        </footer>
      </div>
    </AppShell>
  );
}
