/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZatcaRouteImport } from './routes/zatca'
import { Route as TemplateDesignerRouteImport } from './routes/template-designer'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SystemDataModeRouteImport } from './routes/system-data-mode'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesOrdersRouteImport } from './routes/sales-orders'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductRoadmapRouteImport } from './routes/product-roadmap'
import { Route as PermissionCheckRouteImport } from './routes/permission-check'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HrRouteImport } from './routes/hr'
import { Route as FixedAssetsRouteImport } from './routes/fixed-assets'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DocumentTemplatesRouteImport } from './routes/document-templates'
import { Route as DemoFlowRouteImport } from './routes/demo-flow'
import { Route as DemoChecklistRouteImport } from './routes/demo-checklist'
import { Route as DebitNotesRouteImport } from './routes/debit-notes'
import { Route as DataMigrationRouteImport } from './routes/data-migration'
import { Route as DataIntegrityRouteImport } from './routes/data-integrity'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CustomFieldsRouteImport } from './routes/custom-fields'
import { Route as CreditNotesRouteImport } from './routes/credit-notes'
import { Route as CostCentersRouteImport } from './routes/cost-centers'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BankReconciliationRouteImport } from './routes/bank-reconciliation'
import { Route as BankAccountsRouteImport } from './routes/bank-accounts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as QuotationsIndexRouteImport } from './routes/quotations.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as ReportsVatRouteImport } from './routes/reports.vat'
import { Route as ReportsUnpaidSalesInvoicesRouteImport } from './routes/reports.unpaid-sales-invoices'
import { Route as ReportsTrialBalanceRouteImport } from './routes/reports.trial-balance'
import { Route as ReportsSalesByProductRouteImport } from './routes/reports.sales-by-product'
import { Route as ReportsSalesByCustomerRouteImport } from './routes/reports.sales-by-customer'
import { Route as ReportsProfitLossRouteImport } from './routes/reports.profit-loss'
import { Route as ReportsOverdueSalesInvoicesRouteImport } from './routes/reports.overdue-sales-invoices'
import { Route as ReportsGeneralLedgerRouteImport } from './routes/reports.general-ledger'
import { Route as ReportsCashFlowRouteImport } from './routes/reports.cash-flow'
import { Route as ReportsBalanceSheetRouteImport } from './routes/reports.balance-sheet'
import { Route as ReportsAccountStatementRouteImport } from './routes/reports.account-statement'
import { Route as QuotationsNewRouteImport } from './routes/quotations.new'
import { Route as AuthSelectOrgRouteImport } from './routes/auth.select-org'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AccountingTaxesRouteImport } from './routes/accounting.taxes'
import { Route as AccountingJournalRouteImport } from './routes/accounting.journal'
import { Route as AccountingChartRouteImport } from './routes/accounting.chart'
import { Route as InvoicesSalesIndexRouteImport } from './routes/invoices.sales.index'
import { Route as InvoicesPurchasesIndexRouteImport } from './routes/invoices.purchases.index'
import { Route as AccountingJournalIndexRouteImport } from './routes/accounting.journal.index'
import { Route as QuotationsIdEditRouteImport } from './routes/quotations.$id.edit'
import { Route as InvoicesSalesNewRouteImport } from './routes/invoices.sales.new'
import { Route as InvoicesPurchasesNewRouteImport } from './routes/invoices.purchases.new'
import { Route as AccountingJournalNewRouteImport } from './routes/accounting.journal.new'
import { Route as AccountingJournalIdRouteImport } from './routes/accounting.journal.$id'
import { Route as InvoicesSalesIdEditRouteImport } from './routes/invoices.sales.$id.edit'
import { Route as InvoicesPurchasesIdEditRouteImport } from './routes/invoices.purchases.$id.edit'
import { Route as AccountingJournalIdEditRouteImport } from './routes/accounting.journal.$id.edit'

const ZatcaRoute = ZatcaRouteImport.update({
  id: '/zatca',
  path: '/zatca',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateDesignerRoute = TemplateDesignerRouteImport.update({
  id: '/template-designer',
  path: '/template-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDataModeRoute = SystemDataModeRouteImport.update({
  id: '/system-data-mode',
  path: '/system-data-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoadmapRoute = ProductRoadmapRouteImport.update({
  id: '/product-roadmap',
  path: '/product-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionCheckRoute = PermissionCheckRouteImport.update({
  id: '/permission-check',
  path: '/permission-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedAssetsRoute = FixedAssetsRouteImport.update({
  id: '/fixed-assets',
  path: '/fixed-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentTemplatesRoute = DocumentTemplatesRouteImport.update({
  id: '/document-templates',
  path: '/document-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFlowRoute = DemoFlowRouteImport.update({
  id: '/demo-flow',
  path: '/demo-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoChecklistRoute = DemoChecklistRouteImport.update({
  id: '/demo-checklist',
  path: '/demo-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DebitNotesRoute = DebitNotesRouteImport.update({
  id: '/debit-notes',
  path: '/debit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMigrationRoute = DataMigrationRouteImport.update({
  id: '/data-migration',
  path: '/data-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIntegrityRoute = DataIntegrityRouteImport.update({
  id: '/data-integrity',
  path: '/data-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomFieldsRoute = CustomFieldsRouteImport.update({
  id: '/custom-fields',
  path: '/custom-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditNotesRoute = CreditNotesRouteImport.update({
  id: '/credit-notes',
  path: '/credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CostCentersRoute = CostCentersRouteImport.update({
  id: '/cost-centers',
  path: '/cost-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BankReconciliationRoute = BankReconciliationRouteImport.update({
  id: '/bank-reconciliation',
  path: '/bank-reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const QuotationsIndexRoute = QuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuotationsRoute,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const ReportsVatRoute = ReportsVatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsUnpaidSalesInvoicesRoute =
  ReportsUnpaidSalesInvoicesRouteImport.update({
    id: '/unpaid-sales-invoices',
    path: '/unpaid-sales-invoices',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsTrialBalanceRoute = ReportsTrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSalesByProductRoute = ReportsSalesByProductRouteImport.update({
  id: '/sales-by-product',
  path: '/sales-by-product',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSalesByCustomerRoute = ReportsSalesByCustomerRouteImport.update({
  id: '/sales-by-customer',
  path: '/sales-by-customer',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsProfitLossRoute = ReportsProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsOverdueSalesInvoicesRoute =
  ReportsOverdueSalesInvoicesRouteImport.update({
    id: '/overdue-sales-invoices',
    path: '/overdue-sales-invoices',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsGeneralLedgerRoute = ReportsGeneralLedgerRouteImport.update({
  id: '/general-ledger',
  path: '/general-ledger',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsCashFlowRoute = ReportsCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsBalanceSheetRoute = ReportsBalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsAccountStatementRoute = ReportsAccountStatementRouteImport.update({
  id: '/account-statement',
  path: '/account-statement',
  getParentRoute: () => ReportsRoute,
} as any)
const QuotationsNewRoute = QuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotationsRoute,
} as any)
const AuthSelectOrgRoute = AuthSelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AccountingTaxesRoute = AccountingTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingJournalRoute = AccountingJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingChartRoute = AccountingChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => AccountingRoute,
} as any)
const InvoicesSalesIndexRoute = InvoicesSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesPurchasesIndexRoute = InvoicesPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => InvoicesRoute,
} as any)
const AccountingJournalIndexRoute = AccountingJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountingJournalRoute,
} as any)
const QuotationsIdEditRoute = QuotationsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => QuotationsRoute,
} as any)
const InvoicesSalesNewRoute = InvoicesSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesPurchasesNewRoute = InvoicesPurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const AccountingJournalNewRoute = AccountingJournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccountingJournalRoute,
} as any)
const AccountingJournalIdRoute = AccountingJournalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountingJournalRoute,
} as any)
const InvoicesSalesIdEditRoute = InvoicesSalesIdEditRouteImport.update({
  id: '/sales/$id/edit',
  path: '/sales/$id/edit',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesPurchasesIdEditRoute = InvoicesPurchasesIdEditRouteImport.update({
  id: '/purchases/$id/edit',
  path: '/purchases/$id/edit',
  getParentRoute: () => InvoicesRoute,
} as any)
const AccountingJournalIdEditRoute = AccountingJournalIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AccountingJournalIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRouteWithChildren
  '/bank-accounts': typeof BankAccountsRoute
  '/bank-reconciliation': typeof BankReconciliationRoute
  '/branches': typeof BranchesRoute
  '/communication': typeof CommunicationRoute
  '/cost-centers': typeof CostCentersRoute
  '/credit-notes': typeof CreditNotesRoute
  '/custom-fields': typeof CustomFieldsRoute
  '/customers': typeof CustomersRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/data-migration': typeof DataMigrationRoute
  '/debit-notes': typeof DebitNotesRoute
  '/demo-checklist': typeof DemoChecklistRoute
  '/demo-flow': typeof DemoFlowRoute
  '/document-templates': typeof DocumentTemplatesRoute
  '/employees': typeof EmployeesRoute
  '/fixed-assets': typeof FixedAssetsRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/items': typeof ItemsRoute
  '/payments': typeof PaymentsRoute
  '/permission-check': typeof PermissionCheckRoute
  '/product-roadmap': typeof ProductRoadmapRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotations': typeof QuotationsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sales-orders': typeof SalesOrdersRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/system-data-mode': typeof SystemDataModeRoute
  '/tasks': typeof TasksRoute
  '/template-designer': typeof TemplateDesignerRoute
  '/zatca': typeof ZatcaRoute
  '/accounting/chart': typeof AccountingChartRoute
  '/accounting/journal': typeof AccountingJournalRouteWithChildren
  '/accounting/taxes': typeof AccountingTaxesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/select-org': typeof AuthSelectOrgRoute
  '/quotations/new': typeof QuotationsNewRoute
  '/reports/account-statement': typeof ReportsAccountStatementRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/general-ledger': typeof ReportsGeneralLedgerRoute
  '/reports/overdue-sales-invoices': typeof ReportsOverdueSalesInvoicesRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports/sales-by-customer': typeof ReportsSalesByCustomerRoute
  '/reports/sales-by-product': typeof ReportsSalesByProductRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/unpaid-sales-invoices': typeof ReportsUnpaidSalesInvoicesRoute
  '/reports/vat': typeof ReportsVatRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/accounting/journal/$id': typeof AccountingJournalIdRouteWithChildren
  '/accounting/journal/new': typeof AccountingJournalNewRoute
  '/invoices/purchases/new': typeof InvoicesPurchasesNewRoute
  '/invoices/sales/new': typeof InvoicesSalesNewRoute
  '/quotations/$id/edit': typeof QuotationsIdEditRoute
  '/accounting/journal/': typeof AccountingJournalIndexRoute
  '/invoices/purchases/': typeof InvoicesPurchasesIndexRoute
  '/invoices/sales/': typeof InvoicesSalesIndexRoute
  '/accounting/journal/$id/edit': typeof AccountingJournalIdEditRoute
  '/invoices/purchases/$id/edit': typeof InvoicesPurchasesIdEditRoute
  '/invoices/sales/$id/edit': typeof InvoicesSalesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRouteWithChildren
  '/bank-accounts': typeof BankAccountsRoute
  '/bank-reconciliation': typeof BankReconciliationRoute
  '/branches': typeof BranchesRoute
  '/communication': typeof CommunicationRoute
  '/cost-centers': typeof CostCentersRoute
  '/credit-notes': typeof CreditNotesRoute
  '/custom-fields': typeof CustomFieldsRoute
  '/customers': typeof CustomersRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/data-migration': typeof DataMigrationRoute
  '/debit-notes': typeof DebitNotesRoute
  '/demo-checklist': typeof DemoChecklistRoute
  '/demo-flow': typeof DemoFlowRoute
  '/document-templates': typeof DocumentTemplatesRoute
  '/employees': typeof EmployeesRoute
  '/fixed-assets': typeof FixedAssetsRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/items': typeof ItemsRoute
  '/payments': typeof PaymentsRoute
  '/permission-check': typeof PermissionCheckRoute
  '/product-roadmap': typeof ProductRoadmapRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/receipts': typeof ReceiptsRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/system-data-mode': typeof SystemDataModeRoute
  '/tasks': typeof TasksRoute
  '/template-designer': typeof TemplateDesignerRoute
  '/zatca': typeof ZatcaRoute
  '/accounting/chart': typeof AccountingChartRoute
  '/accounting/taxes': typeof AccountingTaxesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/select-org': typeof AuthSelectOrgRoute
  '/quotations/new': typeof QuotationsNewRoute
  '/reports/account-statement': typeof ReportsAccountStatementRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/general-ledger': typeof ReportsGeneralLedgerRoute
  '/reports/overdue-sales-invoices': typeof ReportsOverdueSalesInvoicesRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports/sales-by-customer': typeof ReportsSalesByCustomerRoute
  '/reports/sales-by-product': typeof ReportsSalesByProductRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/unpaid-sales-invoices': typeof ReportsUnpaidSalesInvoicesRoute
  '/reports/vat': typeof ReportsVatRoute
  '/invoices': typeof InvoicesIndexRoute
  '/quotations': typeof QuotationsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/accounting/journal/$id': typeof AccountingJournalIdRouteWithChildren
  '/accounting/journal/new': typeof AccountingJournalNewRoute
  '/invoices/purchases/new': typeof InvoicesPurchasesNewRoute
  '/invoices/sales/new': typeof InvoicesSalesNewRoute
  '/quotations/$id/edit': typeof QuotationsIdEditRoute
  '/accounting/journal': typeof AccountingJournalIndexRoute
  '/invoices/purchases': typeof InvoicesPurchasesIndexRoute
  '/invoices/sales': typeof InvoicesSalesIndexRoute
  '/accounting/journal/$id/edit': typeof AccountingJournalIdEditRoute
  '/invoices/purchases/$id/edit': typeof InvoicesPurchasesIdEditRoute
  '/invoices/sales/$id/edit': typeof InvoicesSalesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRouteWithChildren
  '/bank-accounts': typeof BankAccountsRoute
  '/bank-reconciliation': typeof BankReconciliationRoute
  '/branches': typeof BranchesRoute
  '/communication': typeof CommunicationRoute
  '/cost-centers': typeof CostCentersRoute
  '/credit-notes': typeof CreditNotesRoute
  '/custom-fields': typeof CustomFieldsRoute
  '/customers': typeof CustomersRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/data-migration': typeof DataMigrationRoute
  '/debit-notes': typeof DebitNotesRoute
  '/demo-checklist': typeof DemoChecklistRoute
  '/demo-flow': typeof DemoFlowRoute
  '/document-templates': typeof DocumentTemplatesRoute
  '/employees': typeof EmployeesRoute
  '/fixed-assets': typeof FixedAssetsRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/items': typeof ItemsRoute
  '/payments': typeof PaymentsRoute
  '/permission-check': typeof PermissionCheckRoute
  '/product-roadmap': typeof ProductRoadmapRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotations': typeof QuotationsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sales-orders': typeof SalesOrdersRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/system-data-mode': typeof SystemDataModeRoute
  '/tasks': typeof TasksRoute
  '/template-designer': typeof TemplateDesignerRoute
  '/zatca': typeof ZatcaRoute
  '/accounting/chart': typeof AccountingChartRoute
  '/accounting/journal': typeof AccountingJournalRouteWithChildren
  '/accounting/taxes': typeof AccountingTaxesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/select-org': typeof AuthSelectOrgRoute
  '/quotations/new': typeof QuotationsNewRoute
  '/reports/account-statement': typeof ReportsAccountStatementRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetRoute
  '/reports/cash-flow': typeof ReportsCashFlowRoute
  '/reports/general-ledger': typeof ReportsGeneralLedgerRoute
  '/reports/overdue-sales-invoices': typeof ReportsOverdueSalesInvoicesRoute
  '/reports/profit-loss': typeof ReportsProfitLossRoute
  '/reports/sales-by-customer': typeof ReportsSalesByCustomerRoute
  '/reports/sales-by-product': typeof ReportsSalesByProductRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/unpaid-sales-invoices': typeof ReportsUnpaidSalesInvoicesRoute
  '/reports/vat': typeof ReportsVatRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/accounting/journal/$id': typeof AccountingJournalIdRouteWithChildren
  '/accounting/journal/new': typeof AccountingJournalNewRoute
  '/invoices/purchases/new': typeof InvoicesPurchasesNewRoute
  '/invoices/sales/new': typeof InvoicesSalesNewRoute
  '/quotations/$id/edit': typeof QuotationsIdEditRoute
  '/accounting/journal/': typeof AccountingJournalIndexRoute
  '/invoices/purchases/': typeof InvoicesPurchasesIndexRoute
  '/invoices/sales/': typeof InvoicesSalesIndexRoute
  '/accounting/journal/$id/edit': typeof AccountingJournalIdEditRoute
  '/invoices/purchases/$id/edit': typeof InvoicesPurchasesIdEditRoute
  '/invoices/sales/$id/edit': typeof InvoicesSalesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/audit-log'
    | '/auth'
    | '/bank-accounts'
    | '/bank-reconciliation'
    | '/branches'
    | '/communication'
    | '/cost-centers'
    | '/credit-notes'
    | '/custom-fields'
    | '/customers'
    | '/data-integrity'
    | '/data-migration'
    | '/debit-notes'
    | '/demo-checklist'
    | '/demo-flow'
    | '/document-templates'
    | '/employees'
    | '/fixed-assets'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/items'
    | '/payments'
    | '/permission-check'
    | '/product-roadmap'
    | '/projects'
    | '/purchase-orders'
    | '/quotations'
    | '/receipts'
    | '/reports'
    | '/sales-orders'
    | '/settings'
    | '/suppliers'
    | '/system-data-mode'
    | '/tasks'
    | '/template-designer'
    | '/zatca'
    | '/accounting/chart'
    | '/accounting/journal'
    | '/accounting/taxes'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/select-org'
    | '/quotations/new'
    | '/reports/account-statement'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/general-ledger'
    | '/reports/overdue-sales-invoices'
    | '/reports/profit-loss'
    | '/reports/sales-by-customer'
    | '/reports/sales-by-product'
    | '/reports/trial-balance'
    | '/reports/unpaid-sales-invoices'
    | '/reports/vat'
    | '/invoices/'
    | '/quotations/'
    | '/reports/'
    | '/accounting/journal/$id'
    | '/accounting/journal/new'
    | '/invoices/purchases/new'
    | '/invoices/sales/new'
    | '/quotations/$id/edit'
    | '/accounting/journal/'
    | '/invoices/purchases/'
    | '/invoices/sales/'
    | '/accounting/journal/$id/edit'
    | '/invoices/purchases/$id/edit'
    | '/invoices/sales/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/audit-log'
    | '/auth'
    | '/bank-accounts'
    | '/bank-reconciliation'
    | '/branches'
    | '/communication'
    | '/cost-centers'
    | '/credit-notes'
    | '/custom-fields'
    | '/customers'
    | '/data-integrity'
    | '/data-migration'
    | '/debit-notes'
    | '/demo-checklist'
    | '/demo-flow'
    | '/document-templates'
    | '/employees'
    | '/fixed-assets'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/items'
    | '/payments'
    | '/permission-check'
    | '/product-roadmap'
    | '/projects'
    | '/purchase-orders'
    | '/receipts'
    | '/sales-orders'
    | '/settings'
    | '/suppliers'
    | '/system-data-mode'
    | '/tasks'
    | '/template-designer'
    | '/zatca'
    | '/accounting/chart'
    | '/accounting/taxes'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/select-org'
    | '/quotations/new'
    | '/reports/account-statement'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/general-ledger'
    | '/reports/overdue-sales-invoices'
    | '/reports/profit-loss'
    | '/reports/sales-by-customer'
    | '/reports/sales-by-product'
    | '/reports/trial-balance'
    | '/reports/unpaid-sales-invoices'
    | '/reports/vat'
    | '/invoices'
    | '/quotations'
    | '/reports'
    | '/accounting/journal/$id'
    | '/accounting/journal/new'
    | '/invoices/purchases/new'
    | '/invoices/sales/new'
    | '/quotations/$id/edit'
    | '/accounting/journal'
    | '/invoices/purchases'
    | '/invoices/sales'
    | '/accounting/journal/$id/edit'
    | '/invoices/purchases/$id/edit'
    | '/invoices/sales/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/audit-log'
    | '/auth'
    | '/bank-accounts'
    | '/bank-reconciliation'
    | '/branches'
    | '/communication'
    | '/cost-centers'
    | '/credit-notes'
    | '/custom-fields'
    | '/customers'
    | '/data-integrity'
    | '/data-migration'
    | '/debit-notes'
    | '/demo-checklist'
    | '/demo-flow'
    | '/document-templates'
    | '/employees'
    | '/fixed-assets'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/items'
    | '/payments'
    | '/permission-check'
    | '/product-roadmap'
    | '/projects'
    | '/purchase-orders'
    | '/quotations'
    | '/receipts'
    | '/reports'
    | '/sales-orders'
    | '/settings'
    | '/suppliers'
    | '/system-data-mode'
    | '/tasks'
    | '/template-designer'
    | '/zatca'
    | '/accounting/chart'
    | '/accounting/journal'
    | '/accounting/taxes'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/select-org'
    | '/quotations/new'
    | '/reports/account-statement'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/general-ledger'
    | '/reports/overdue-sales-invoices'
    | '/reports/profit-loss'
    | '/reports/sales-by-customer'
    | '/reports/sales-by-product'
    | '/reports/trial-balance'
    | '/reports/unpaid-sales-invoices'
    | '/reports/vat'
    | '/invoices/'
    | '/quotations/'
    | '/reports/'
    | '/accounting/journal/$id'
    | '/accounting/journal/new'
    | '/invoices/purchases/new'
    | '/invoices/sales/new'
    | '/quotations/$id/edit'
    | '/accounting/journal/'
    | '/invoices/purchases/'
    | '/invoices/sales/'
    | '/accounting/journal/$id/edit'
    | '/invoices/purchases/$id/edit'
    | '/invoices/sales/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRouteWithChildren
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRouteWithChildren
  BankAccountsRoute: typeof BankAccountsRoute
  BankReconciliationRoute: typeof BankReconciliationRoute
  BranchesRoute: typeof BranchesRoute
  CommunicationRoute: typeof CommunicationRoute
  CostCentersRoute: typeof CostCentersRoute
  CreditNotesRoute: typeof CreditNotesRoute
  CustomFieldsRoute: typeof CustomFieldsRoute
  CustomersRoute: typeof CustomersRoute
  DataIntegrityRoute: typeof DataIntegrityRoute
  DataMigrationRoute: typeof DataMigrationRoute
  DebitNotesRoute: typeof DebitNotesRoute
  DemoChecklistRoute: typeof DemoChecklistRoute
  DemoFlowRoute: typeof DemoFlowRoute
  DocumentTemplatesRoute: typeof DocumentTemplatesRoute
  EmployeesRoute: typeof EmployeesRoute
  FixedAssetsRoute: typeof FixedAssetsRoute
  HrRoute: typeof HrRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  ItemsRoute: typeof ItemsRoute
  PaymentsRoute: typeof PaymentsRoute
  PermissionCheckRoute: typeof PermissionCheckRoute
  ProductRoadmapRoute: typeof ProductRoadmapRoute
  ProjectsRoute: typeof ProjectsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  QuotationsRoute: typeof QuotationsRouteWithChildren
  ReceiptsRoute: typeof ReceiptsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SalesOrdersRoute: typeof SalesOrdersRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  SystemDataModeRoute: typeof SystemDataModeRoute
  TasksRoute: typeof TasksRoute
  TemplateDesignerRoute: typeof TemplateDesignerRoute
  ZatcaRoute: typeof ZatcaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zatca': {
      id: '/zatca'
      path: '/zatca'
      fullPath: '/zatca'
      preLoaderRoute: typeof ZatcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-designer': {
      id: '/template-designer'
      path: '/template-designer'
      fullPath: '/template-designer'
      preLoaderRoute: typeof TemplateDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-data-mode': {
      id: '/system-data-mode'
      path: '/system-data-mode'
      fullPath: '/system-data-mode'
      preLoaderRoute: typeof SystemDataModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders': {
      id: '/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-roadmap': {
      id: '/product-roadmap'
      path: '/product-roadmap'
      fullPath: '/product-roadmap'
      preLoaderRoute: typeof ProductRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permission-check': {
      id: '/permission-check'
      path: '/permission-check'
      fullPath: '/permission-check'
      preLoaderRoute: typeof PermissionCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-assets': {
      id: '/fixed-assets'
      path: '/fixed-assets'
      fullPath: '/fixed-assets'
      preLoaderRoute: typeof FixedAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-templates': {
      id: '/document-templates'
      path: '/document-templates'
      fullPath: '/document-templates'
      preLoaderRoute: typeof DocumentTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-flow': {
      id: '/demo-flow'
      path: '/demo-flow'
      fullPath: '/demo-flow'
      preLoaderRoute: typeof DemoFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-checklist': {
      id: '/demo-checklist'
      path: '/demo-checklist'
      fullPath: '/demo-checklist'
      preLoaderRoute: typeof DemoChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debit-notes': {
      id: '/debit-notes'
      path: '/debit-notes'
      fullPath: '/debit-notes'
      preLoaderRoute: typeof DebitNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-migration': {
      id: '/data-migration'
      path: '/data-migration'
      fullPath: '/data-migration'
      preLoaderRoute: typeof DataMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-integrity': {
      id: '/data-integrity'
      path: '/data-integrity'
      fullPath: '/data-integrity'
      preLoaderRoute: typeof DataIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-fields': {
      id: '/custom-fields'
      path: '/custom-fields'
      fullPath: '/custom-fields'
      preLoaderRoute: typeof CustomFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-notes': {
      id: '/credit-notes'
      path: '/credit-notes'
      fullPath: '/credit-notes'
      preLoaderRoute: typeof CreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-centers': {
      id: '/cost-centers'
      path: '/cost-centers'
      fullPath: '/cost-centers'
      preLoaderRoute: typeof CostCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-reconciliation': {
      id: '/bank-reconciliation'
      path: '/bank-reconciliation'
      fullPath: '/bank-reconciliation'
      preLoaderRoute: typeof BankReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts': {
      id: '/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/quotations/': {
      id: '/quotations/'
      path: '/'
      fullPath: '/quotations/'
      preLoaderRoute: typeof QuotationsIndexRouteImport
      parentRoute: typeof QuotationsRoute
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/reports/vat': {
      id: '/reports/vat'
      path: '/vat'
      fullPath: '/reports/vat'
      preLoaderRoute: typeof ReportsVatRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/unpaid-sales-invoices': {
      id: '/reports/unpaid-sales-invoices'
      path: '/unpaid-sales-invoices'
      fullPath: '/reports/unpaid-sales-invoices'
      preLoaderRoute: typeof ReportsUnpaidSalesInvoicesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/trial-balance': {
      id: '/reports/trial-balance'
      path: '/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof ReportsTrialBalanceRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/sales-by-product': {
      id: '/reports/sales-by-product'
      path: '/sales-by-product'
      fullPath: '/reports/sales-by-product'
      preLoaderRoute: typeof ReportsSalesByProductRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/sales-by-customer': {
      id: '/reports/sales-by-customer'
      path: '/sales-by-customer'
      fullPath: '/reports/sales-by-customer'
      preLoaderRoute: typeof ReportsSalesByCustomerRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/profit-loss': {
      id: '/reports/profit-loss'
      path: '/profit-loss'
      fullPath: '/reports/profit-loss'
      preLoaderRoute: typeof ReportsProfitLossRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/overdue-sales-invoices': {
      id: '/reports/overdue-sales-invoices'
      path: '/overdue-sales-invoices'
      fullPath: '/reports/overdue-sales-invoices'
      preLoaderRoute: typeof ReportsOverdueSalesInvoicesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/general-ledger': {
      id: '/reports/general-ledger'
      path: '/general-ledger'
      fullPath: '/reports/general-ledger'
      preLoaderRoute: typeof ReportsGeneralLedgerRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/cash-flow': {
      id: '/reports/cash-flow'
      path: '/cash-flow'
      fullPath: '/reports/cash-flow'
      preLoaderRoute: typeof ReportsCashFlowRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/balance-sheet': {
      id: '/reports/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof ReportsBalanceSheetRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/account-statement': {
      id: '/reports/account-statement'
      path: '/account-statement'
      fullPath: '/reports/account-statement'
      preLoaderRoute: typeof ReportsAccountStatementRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/quotations/new': {
      id: '/quotations/new'
      path: '/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof QuotationsNewRouteImport
      parentRoute: typeof QuotationsRoute
    }
    '/auth/select-org': {
      id: '/auth/select-org'
      path: '/select-org'
      fullPath: '/auth/select-org'
      preLoaderRoute: typeof AuthSelectOrgRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/accounting/taxes': {
      id: '/accounting/taxes'
      path: '/taxes'
      fullPath: '/accounting/taxes'
      preLoaderRoute: typeof AccountingTaxesRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/journal': {
      id: '/accounting/journal'
      path: '/journal'
      fullPath: '/accounting/journal'
      preLoaderRoute: typeof AccountingJournalRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/chart': {
      id: '/accounting/chart'
      path: '/chart'
      fullPath: '/accounting/chart'
      preLoaderRoute: typeof AccountingChartRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/invoices/sales/': {
      id: '/invoices/sales/'
      path: '/sales'
      fullPath: '/invoices/sales/'
      preLoaderRoute: typeof InvoicesSalesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/purchases/': {
      id: '/invoices/purchases/'
      path: '/purchases'
      fullPath: '/invoices/purchases/'
      preLoaderRoute: typeof InvoicesPurchasesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/accounting/journal/': {
      id: '/accounting/journal/'
      path: '/'
      fullPath: '/accounting/journal/'
      preLoaderRoute: typeof AccountingJournalIndexRouteImport
      parentRoute: typeof AccountingJournalRoute
    }
    '/quotations/$id/edit': {
      id: '/quotations/$id/edit'
      path: '/$id/edit'
      fullPath: '/quotations/$id/edit'
      preLoaderRoute: typeof QuotationsIdEditRouteImport
      parentRoute: typeof QuotationsRoute
    }
    '/invoices/sales/new': {
      id: '/invoices/sales/new'
      path: '/sales/new'
      fullPath: '/invoices/sales/new'
      preLoaderRoute: typeof InvoicesSalesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/purchases/new': {
      id: '/invoices/purchases/new'
      path: '/purchases/new'
      fullPath: '/invoices/purchases/new'
      preLoaderRoute: typeof InvoicesPurchasesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/accounting/journal/new': {
      id: '/accounting/journal/new'
      path: '/new'
      fullPath: '/accounting/journal/new'
      preLoaderRoute: typeof AccountingJournalNewRouteImport
      parentRoute: typeof AccountingJournalRoute
    }
    '/accounting/journal/$id': {
      id: '/accounting/journal/$id'
      path: '/$id'
      fullPath: '/accounting/journal/$id'
      preLoaderRoute: typeof AccountingJournalIdRouteImport
      parentRoute: typeof AccountingJournalRoute
    }
    '/invoices/sales/$id/edit': {
      id: '/invoices/sales/$id/edit'
      path: '/sales/$id/edit'
      fullPath: '/invoices/sales/$id/edit'
      preLoaderRoute: typeof InvoicesSalesIdEditRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/purchases/$id/edit': {
      id: '/invoices/purchases/$id/edit'
      path: '/purchases/$id/edit'
      fullPath: '/invoices/purchases/$id/edit'
      preLoaderRoute: typeof InvoicesPurchasesIdEditRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/accounting/journal/$id/edit': {
      id: '/accounting/journal/$id/edit'
      path: '/edit'
      fullPath: '/accounting/journal/$id/edit'
      preLoaderRoute: typeof AccountingJournalIdEditRouteImport
      parentRoute: typeof AccountingJournalIdRoute
    }
  }
}

interface AccountingJournalIdRouteChildren {
  AccountingJournalIdEditRoute: typeof AccountingJournalIdEditRoute
}

const AccountingJournalIdRouteChildren: AccountingJournalIdRouteChildren = {
  AccountingJournalIdEditRoute: AccountingJournalIdEditRoute,
}

const AccountingJournalIdRouteWithChildren =
  AccountingJournalIdRoute._addFileChildren(AccountingJournalIdRouteChildren)

interface AccountingJournalRouteChildren {
  AccountingJournalIdRoute: typeof AccountingJournalIdRouteWithChildren
  AccountingJournalNewRoute: typeof AccountingJournalNewRoute
  AccountingJournalIndexRoute: typeof AccountingJournalIndexRoute
}

const AccountingJournalRouteChildren: AccountingJournalRouteChildren = {
  AccountingJournalIdRoute: AccountingJournalIdRouteWithChildren,
  AccountingJournalNewRoute: AccountingJournalNewRoute,
  AccountingJournalIndexRoute: AccountingJournalIndexRoute,
}

const AccountingJournalRouteWithChildren =
  AccountingJournalRoute._addFileChildren(AccountingJournalRouteChildren)

interface AccountingRouteChildren {
  AccountingChartRoute: typeof AccountingChartRoute
  AccountingJournalRoute: typeof AccountingJournalRouteWithChildren
  AccountingTaxesRoute: typeof AccountingTaxesRoute
}

const AccountingRouteChildren: AccountingRouteChildren = {
  AccountingChartRoute: AccountingChartRoute,
  AccountingJournalRoute: AccountingJournalRouteWithChildren,
  AccountingTaxesRoute: AccountingTaxesRoute,
}

const AccountingRouteWithChildren = AccountingRoute._addFileChildren(
  AccountingRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSelectOrgRoute: typeof AuthSelectOrgRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSelectOrgRoute: AuthSelectOrgRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface InvoicesRouteChildren {
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  InvoicesPurchasesNewRoute: typeof InvoicesPurchasesNewRoute
  InvoicesSalesNewRoute: typeof InvoicesSalesNewRoute
  InvoicesPurchasesIndexRoute: typeof InvoicesPurchasesIndexRoute
  InvoicesSalesIndexRoute: typeof InvoicesSalesIndexRoute
  InvoicesPurchasesIdEditRoute: typeof InvoicesPurchasesIdEditRoute
  InvoicesSalesIdEditRoute: typeof InvoicesSalesIdEditRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIndexRoute: InvoicesIndexRoute,
  InvoicesPurchasesNewRoute: InvoicesPurchasesNewRoute,
  InvoicesSalesNewRoute: InvoicesSalesNewRoute,
  InvoicesPurchasesIndexRoute: InvoicesPurchasesIndexRoute,
  InvoicesSalesIndexRoute: InvoicesSalesIndexRoute,
  InvoicesPurchasesIdEditRoute: InvoicesPurchasesIdEditRoute,
  InvoicesSalesIdEditRoute: InvoicesSalesIdEditRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface QuotationsRouteChildren {
  QuotationsNewRoute: typeof QuotationsNewRoute
  QuotationsIndexRoute: typeof QuotationsIndexRoute
  QuotationsIdEditRoute: typeof QuotationsIdEditRoute
}

const QuotationsRouteChildren: QuotationsRouteChildren = {
  QuotationsNewRoute: QuotationsNewRoute,
  QuotationsIndexRoute: QuotationsIndexRoute,
  QuotationsIdEditRoute: QuotationsIdEditRoute,
}

const QuotationsRouteWithChildren = QuotationsRoute._addFileChildren(
  QuotationsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsAccountStatementRoute: typeof ReportsAccountStatementRoute
  ReportsBalanceSheetRoute: typeof ReportsBalanceSheetRoute
  ReportsCashFlowRoute: typeof ReportsCashFlowRoute
  ReportsGeneralLedgerRoute: typeof ReportsGeneralLedgerRoute
  ReportsOverdueSalesInvoicesRoute: typeof ReportsOverdueSalesInvoicesRoute
  ReportsProfitLossRoute: typeof ReportsProfitLossRoute
  ReportsSalesByCustomerRoute: typeof ReportsSalesByCustomerRoute
  ReportsSalesByProductRoute: typeof ReportsSalesByProductRoute
  ReportsTrialBalanceRoute: typeof ReportsTrialBalanceRoute
  ReportsUnpaidSalesInvoicesRoute: typeof ReportsUnpaidSalesInvoicesRoute
  ReportsVatRoute: typeof ReportsVatRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsAccountStatementRoute: ReportsAccountStatementRoute,
  ReportsBalanceSheetRoute: ReportsBalanceSheetRoute,
  ReportsCashFlowRoute: ReportsCashFlowRoute,
  ReportsGeneralLedgerRoute: ReportsGeneralLedgerRoute,
  ReportsOverdueSalesInvoicesRoute: ReportsOverdueSalesInvoicesRoute,
  ReportsProfitLossRoute: ReportsProfitLossRoute,
  ReportsSalesByCustomerRoute: ReportsSalesByCustomerRoute,
  ReportsSalesByProductRoute: ReportsSalesByProductRoute,
  ReportsTrialBalanceRoute: ReportsTrialBalanceRoute,
  ReportsUnpaidSalesInvoicesRoute: ReportsUnpaidSalesInvoicesRoute,
  ReportsVatRoute: ReportsVatRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRouteWithChildren,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRouteWithChildren,
  BankAccountsRoute: BankAccountsRoute,
  BankReconciliationRoute: BankReconciliationRoute,
  BranchesRoute: BranchesRoute,
  CommunicationRoute: CommunicationRoute,
  CostCentersRoute: CostCentersRoute,
  CreditNotesRoute: CreditNotesRoute,
  CustomFieldsRoute: CustomFieldsRoute,
  CustomersRoute: CustomersRoute,
  DataIntegrityRoute: DataIntegrityRoute,
  DataMigrationRoute: DataMigrationRoute,
  DebitNotesRoute: DebitNotesRoute,
  DemoChecklistRoute: DemoChecklistRoute,
  DemoFlowRoute: DemoFlowRoute,
  DocumentTemplatesRoute: DocumentTemplatesRoute,
  EmployeesRoute: EmployeesRoute,
  FixedAssetsRoute: FixedAssetsRoute,
  HrRoute: HrRoute,
  IntegrationsRoute: IntegrationsRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  ItemsRoute: ItemsRoute,
  PaymentsRoute: PaymentsRoute,
  PermissionCheckRoute: PermissionCheckRoute,
  ProductRoadmapRoute: ProductRoadmapRoute,
  ProjectsRoute: ProjectsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  QuotationsRoute: QuotationsRouteWithChildren,
  ReceiptsRoute: ReceiptsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SalesOrdersRoute: SalesOrdersRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  SystemDataModeRoute: SystemDataModeRoute,
  TasksRoute: TasksRoute,
  TemplateDesignerRoute: TemplateDesignerRoute,
  ZatcaRoute: ZatcaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
